// Build script: src/styles.css + assets/*.webp -> client.js
//
// The DeepSeek Harness web shell materializes the `./client` export of this
// package, so client.js MUST be a committed artifact. Run this after editing
// src/styles.css or swapping the whale art:
//
//   node build.js
//
// It injects the two WebP assets as base64 data URIs into the __WHALE_LIGHT__
// / __WHALE_DARK__ placeholders and wraps the stylesheet in the client module
// loader bundle shape the shell expects.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const read = (rel) => fs.readFileSync(path.join(ROOT, rel), "utf8");
const readB64 = (rel) => fs.readFileSync(path.join(ROOT, rel)).toString("base64");

const css = read("src/styles.css")
  .replaceAll("__WHALE_LIGHT__", readB64("assets/whale-light.webp"))
  .replaceAll("__WHALE_DARK__", readB64("assets/whale-dark.webp"));

if (css.includes("__WHALE_")) {
  console.error("ERROR: placeholders left unresolved in styles.css");
  process.exit(1);
}

const bundle = `/* ============================================================
   dsh-ui-crystal — Crystal UI theme for DeepSeek Harness
   Pure-CSS client plugin. The bundle registers a factory on the
   client module loader; materializing it injects one <style> tag
   that overrides the --dsw-* design tokens (and a few stable
   attribute-hooked surfaces). Injected after every stock plugin,
   so equal-specificity rules win the cascade.
   GENERATED BY build.js — edit src/styles.css, not this file.
   ============================================================ */
window.__ModuleLoader__.load({
	id: "dsh-ui-crystal",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
		const css = \`${css}\`;
		const tagId = "dsh-ui-crystal/theme.css";
		if (typeof document !== "undefined" && document.querySelector("style[data-plugin-css=" + JSON.stringify(tagId) + "]") === null) {
			const tag = document.createElement("style");
			tag.dataset.plugin = "dsh-ui-crystal";
			tag.dataset.pluginCss = tagId;
			tag.textContent = css;
			document.head.appendChild(tag);
		}
		// Cordis plugin shape: the loader applies the entry's exports, so even a
		// pure-CSS client plugin must expose apply. Injection already happened
		// at materialization above; apply itself is a no-op.
		var apply = function() {};
		exports.apply = apply;
		return module.exports;
	}
});
`;

fs.writeFileSync(path.join(ROOT, "client.js"), bundle);
console.log("built client.js:", bundle.length, "bytes");
